name: publish-gh-pages

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "0 12 * * 1,3"

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout github pages branch"
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: "Fetch main branch in a worktree so we can access the files"
        run: |
          git fetch origin main --depth 1
          git worktree add --checkout ${RUNNER_TEMP}/main-branch/ origin/main
      - name: "Generate site into the gh-pages branch"
        run: |
          (
            cd "${RUNNER_TEMP}/main-branch/"
            bash ./generate-lyrics.sh > ./lyrics.js
          )
          files_to_copy=(
            index.html
            style.css
            vue.js
            lyrics.js
          )
          date_format=$( TZ=America/Chicago date +"%Y-%m-%d %-l:%M:%S %p %Z" )
          for f in "${files_to_copy[@]}"; do
            cp -r -v ${RUNNER_TEMP}/main-branch/"$f" "./${f}"
            if [[ -f "$f" ]]; then
              sed -i -e "s/CACHE_BUSTING_STRING/$( date  +%s )/g" "./${f}"
              sed -i -e "s/LAST_UPDATE_TIME/${date_format}/g" "./${f}"
            fi
            git add "./${f}"
          done
      - name: "Push the changes to gh-pages"
        run: |
          git config --global user.name 'Oliver Isaac (GH Actions)'
          git config --global user.email 'oliverisaac@users.noreply.github.com'
          git commit -am "Automated report"
          git push origin gh-pages
